// Türkiye'nin 81 ili ve ilçeleri
export const CITY_DISTRICTS: Record<string, string[]> = {
  'Adana': ['Seyhan', 'Çukurova', 'Yüreğir', 'Sarıçam', 'Ceyhan', 'Kozan', 'İmamoğlu', 'Karaisalı', 'Karataş', 'Pozantı', 'Aladağ', 'Feke', 'Saimbeyli', 'Tufanbeyli', 'Yumurtalık'],
  'Adıyaman': ['Merkez', 'Kahta', 'Besni', 'Gölbaşı', 'Gerger', 'Çelikhan', 'Samsat', 'Sincik', 'Tut'],
  'Afyonkarahisar': ['Merkez', 'Sandıklı', 'Dinar', 'Bolvadin', 'Emirdağ', 'Çay', 'Sultandağı', 'Sinanpaşa', 'İhsaniye', 'İscehisar', 'Şuhut', 'Başmakçı', 'Bayat', 'Dazkırı', 'Evciler', 'Hocalar', 'Kızılören'],
  'Ağrı': ['Merkez', 'Doğubayazıt', 'Patnos', 'Diyadin', 'Eleşkirt', 'Hamur', 'Taşlıçay', 'Tutak'],
  'Aksaray': ['Merkez', 'Ortaköy', 'Eskil', 'Güzelyurt', 'Ağaçören', 'Gülağaç', 'Sarıyahşi'],
  'Amasya': ['Merkez', 'Merzifon', 'Suluova', 'Taşova', 'Göynücek', 'Gümüşhacıköy', 'Hamamözü'],
  'Ankara': ['Çankaya', 'Keçiören', 'Yenimahalle', 'Mamak', 'Etimesgut', 'Sincan', 'Altındağ', 'Pursaklar', 'Gölbaşı', 'Polatlı', 'Beypazarı', 'Çubuk', 'Haymana', 'Kahramankazan', 'Kızılcahamam', 'Şereflikoçhisar', 'Akyurt', 'Ayaş', 'Bala', 'Çamlıdere', 'Elmadağ', 'Evren', 'Güdül', 'Kalecik', 'Nallıhan'],
  'Antalya': ['Muratpaşa', 'Kepez', 'Konyaaltı', 'Alanya', 'Manavgat', 'Serik', 'Kumluca', 'Kaş', 'Kemer', 'Aksu', 'Döşemealtı', 'Finike', 'Gazipaşa', 'Demre', 'Elmalı', 'Gündoğmuş', 'İbradı', 'Akseki', 'Korkuteli'],
  'Ardahan': ['Merkez', 'Göle', 'Çıldır', 'Hanak', 'Posof', 'Damal'],
  'Artvin': ['Merkez', 'Hopa', 'Borçka', 'Arhavi', 'Şavşat', 'Yusufeli', 'Ardanuç', 'Murgul'],
  'Aydın': ['Efeler', 'Nazilli', 'Söke', 'Kuşadası', 'Didim', 'İncirliova', 'Germencik', 'Çine', 'Sultanhisar', 'Bozdoğan', 'Buharkent', 'Karacasu', 'Karpuzlu', 'Koçarlı', 'Köşk', 'Kuyucak', 'Yenipazar'],
  'Balıkesir': ['Altıeylül', 'Karesi', 'Bandırma', 'Edremit', 'Gönen', 'Erdek', 'Burhaniye', 'Ayvalık', 'Susurluk', 'Bigadiç', 'Dursunbey', 'Havran', 'İvrindi', 'Kepsut', 'Manyas', 'Savaştepe', 'Sındırgı', 'Balya', 'Marmara'],
  'Bartın': ['Merkez', 'Ulus', 'Kurucaşile', 'Amasra'],
  'Batman': ['Merkez', 'Sason', 'Kozluk', 'Beşiri', 'Gercüş', 'Hasankeyf'],
  'Bayburt': ['Merkez', 'Demirözü', 'Aydıntepe'],
  'Bilecik': ['Merkez', 'Bozüyük', 'Osmaneli', 'Söğüt', 'Gölpazarı', 'İnhisar', 'Pazaryeri', 'Yenipazar'],
  'Bingöl': ['Merkez', 'Genç', 'Solhan', 'Karlıova', 'Adaklı', 'Kiğı', 'Yayladere', 'Yedisu'],
  'Bitlis': ['Merkez', 'Tatvan', 'Ahlat', 'Güroymak', 'Adilcevaz', 'Hizan', 'Mutki'],
  'Bolu': ['Merkez', 'Gerede', 'Mudurnu', 'Göynük', 'Mengen', 'Yeniçağa', 'Dörtdivan', 'Kıbrıscık', 'Seben'],
  'Burdur': ['Merkez', 'Bucak', 'Gölhisar', 'Yeşilova', 'Ağlasun', 'Altınyayla', 'Çavdır', 'Çeltikçi', 'Karamanlı', 'Kemer', 'Tefenni'],
  'Bursa': ['Osmangazi', 'Nilüfer', 'Yıldırım', 'İnegöl', 'Gemlik', 'Mudanya', 'Gürsu', 'Kestel', 'Karacabey', 'Mustafakemalpaşa', 'Orhangazi', 'İznik', 'Yenişehir', 'Orhaneli', 'Keles', 'Büyükorhan', 'Harmancık'],
  'Çanakkale': ['Merkez', 'Biga', 'Çan', 'Gelibolu', 'Lapseki', 'Ayvacık', 'Bayramiç', 'Eceabat', 'Ezine', 'Gökçeada', 'Yenice', 'Bozcaada'],
  'Çankırı': ['Merkez', 'Çerkeş', 'Ilgaz', 'Şabanözü', 'Kurşunlu', 'Eldivan', 'Yapraklı', 'Atkaracalar', 'Bayramören', 'Kızılırmak', 'Korgun', 'Orta'],
  'Çorum': ['Merkez', 'Sungurlu', 'Osmancık', 'Alaca', 'İskilip', 'Bayat', 'Kargı', 'Mecitözü', 'Boğazkale', 'Dodurga', 'Laçin', 'Oğuzlar', 'Ortaköy', 'Uğurludağ'],
  'Denizli': ['Merkezefendi', 'Pamukkale', 'Çivril', 'Acıpayam', 'Buldan', 'Tavas', 'Sarayköy', 'Honaz', 'Kale', 'Çal', 'Çameli', 'Güney', 'Serinhisar', 'Bekilli', 'Beyağaç', 'Baklan', 'Babadağ', 'Bozkurt', 'Çardak'],
  'Diyarbakır': ['Bağlar', 'Kayapınar', 'Yenişehir', 'Sur', 'Bismil', 'Ergani', 'Silvan', 'Çınar', 'Çermik', 'Kulp', 'Lice', 'Hani', 'Dicle', 'Eğil', 'Hazro', 'Kocaköy', 'Çüngüş'],
  'Düzce': ['Merkez', 'Akçakoca', 'Gölyaka', 'Cumayeri', 'Çilimli', 'Gümüşova', 'Kaynaşlı', 'Yığılca'],
  'Edirne': ['Merkez', 'Keşan', 'Uzunköprü', 'İpsala', 'Havsa', 'Enez', 'Meriç', 'Süloğlu', 'Lalapaşa'],
  'Elazığ': ['Merkez', 'Kovancılar', 'Karakoçan', 'Palu', 'Baskil', 'Maden', 'Sivrice', 'Keban', 'Arıcak', 'Alacakaya', 'Ağın'],
  'Erzincan': ['Merkez', 'Üzümlü', 'Tercan', 'Refahiye', 'Çayırlı', 'İliç', 'Kemah', 'Kemaliye', 'Otlukbeli'],
  'Erzurum': ['Yakutiye', 'Palandöken', 'Aziziye', 'Oltu', 'Horasan', 'Pasinler', 'Hınıs', 'Karayazı', 'Aşkale', 'İspir', 'Narman', 'Olur', 'Şenkaya', 'Tekman', 'Tortum', 'Uzundere', 'Çat', 'Karaçoban', 'Köprüköy', 'Pazaryolu'],
  'Eskişehir': ['Odunpazarı', 'Tepebaşı', 'Çifteler', 'Sivrihisar', 'Alpu', 'Beylikova', 'Günyüzü', 'Han', 'İnönü', 'Mahmudiye', 'Mihalgazi', 'Mihallıççık', 'Sarıcakaya', 'Seyitgazi'],
  'Gaziantep': ['Şahinbey', 'Şehitkamil', 'Nizip', 'İslahiye', 'Nurdağı', 'Oğuzeli', 'Araban', 'Karkamış', 'Yavuzeli'],
  'Giresun': ['Merkez', 'Bulancak', 'Görele', 'Espiye', 'Tirebolu', 'Eynesil', 'Piraziz', 'Keşap', 'Dereli', 'Yağlıdere', 'Güce', 'Alucra', 'Çamoluk', 'Çanakçı', 'Doğankent', 'Şebinkarahisar'],
  'Gümüşhane': ['Merkez', 'Kelkit', 'Şiran', 'Torul', 'Kürtün', 'Köse'],
  'Hakkâri': ['Merkez', 'Yüksekova', 'Çukurca', 'Şemdinli', 'Derecik'],
  'Hatay': ['Antakya', 'İskenderun', 'Defne', 'Samandağ', 'Dörtyol', 'Reyhanlı', 'Kırıkhan', 'Erzin', 'Arsuz', 'Payas', 'Altınözü', 'Belen', 'Hassa', 'Kumlu', 'Yayladağı'],
  'Iğdır': ['Merkez', 'Tuzluca', 'Aralık', 'Karakoyunlu'],
  'Isparta': ['Merkez', 'Yalvaç', 'Eğirdir', 'Şarkikaraağaç', 'Gelendost', 'Senirkent', 'Keçiborlu', 'Sütçüler', 'Uluborlu', 'Aksu', 'Atabey', 'Gönen', 'Yenişarbademli'],
  'İstanbul': ['Kadıköy', 'Beşiktaş', 'Üsküdar', 'Ataşehir', 'Maltepe', 'Kartal', 'Pendik', 'Bakırköy', 'Beyoğlu', 'Şişli', 'Fatih', 'Sarıyer', 'Beykoz', 'Başakşehir', 'Esenyurt', 'Bağcılar', 'Bahçelievler', 'Esenler', 'Sultanbeyli', 'Tuzla', 'Ümraniye', 'Küçükçekmece', 'Büyükçekmece', 'Bayrampaşa', 'Güngören', 'Kağıthane', 'Zeytinburnu', 'Gaziosmanpaşa', 'Sultangazi', 'Eyüpsultan', 'Sancaktepe', 'Çekmeköy', 'Arnavutköy', 'Beylikdüzü', 'Avcılar', 'Silivri', 'Şile', 'Adalar', 'Çatalca'],
  'İzmir': ['Konak', 'Karşıyaka', 'Bornova', 'Buca', 'Bayraklı', 'Çiğli', 'Gaziemir', 'Balçova', 'Karabağlar', 'Narlıdere', 'Menemen', 'Torbalı', 'Tire', 'Ödemiş', 'Bergama', 'Aliağa', 'Menderes', 'Seferihisar', 'Urla', 'Çeşme', 'Foça', 'Kemalpaşa', 'Kiraz', 'Kınık', 'Bayındır', 'Selçuk', 'Dikili', 'Güzelbahçe', 'Beydağ', 'Karaburun'],
  'Kahramanmaraş': ['Onikişubat', 'Dulkadiroğlu', 'Elbistan', 'Afşin', 'Türkoğlu', 'Göksun', 'Pazarcık', 'Andırın', 'Çağlayancerit', 'Ekinözü', 'Nurhak'],
  'Karabük': ['Merkez', 'Safranbolu', 'Eskipazar', 'Yenice', 'Ovacık', 'Eflani'],
  'Karaman': ['Merkez', 'Ermenek', 'Sarıveliler', 'Ayrancı', 'Kazımkarabekir', 'Başyayla'],
  'Kars': ['Merkez', 'Sarıkamış', 'Kağızman', 'Selim', 'Susuz', 'Arpaçay', 'Digor', 'Akyaka'],
  'Kastamonu': ['Merkez', 'Tosya', 'Taşköprü', 'İnebolu', 'Cide', 'Araç', 'Daday', 'Devrekani', 'İhsangazi', 'Küre', 'Çatalzeytin', 'Abana', 'Azdavay', 'Bozkurt', 'Doğanyurt', 'Hanönü', 'Pınarbaşı', 'Seydiler', 'Şenpazar'],
  'Kayseri': ['Melikgazi', 'Kocasinan', 'Talas', 'İncesu', 'Develi', 'Bünyan', 'Tomarza', 'Yahyalı', 'Yeşilhisar', 'Hacılar', 'Pınarbaşı', 'Sarıoğlan', 'Sarız', 'Akkışla', 'Felahiye', 'Özvatan'],
  'Kilis': ['Merkez', 'Musabeyli', 'Elbeyli', 'Polateli'],
  'Kırıkkale': ['Merkez', 'Keskin', 'Delice', 'Yahşihan', 'Bahşili', 'Balışeyh', 'Çelebi', 'Karakeçili', 'Sulakyurt'],
  'Kırklareli': ['Merkez', 'Lüleburgaz', 'Babaeski', 'Vize', 'Pınarhisar', 'Demirköy', 'Kofçaz', 'Pehlivanköy'],
  'Kırşehir': ['Merkez', 'Kaman', 'Mucur', 'Çiçekdağı', 'Akçakent', 'Akpınar', 'Boztepe'],
  'Kocaeli': ['İzmit', 'Gebze', 'Darıca', 'Çayırova', 'Derince', 'Gölcük', 'Kartepe', 'Kandıra', 'Karamürsel', 'Körfez', 'Başiskele', 'Dilovası'],
  'Konya': ['Selçuklu', 'Meram', 'Karatay', 'Ereğli', 'Akşehir', 'Beyşehir', 'Çumra', 'Ilgın', 'Kulu', 'Cihanbeyli', 'Seydişehir', 'Karapınar', 'Bozkır', 'Sarayönü', 'Kadınhanı', 'Doğanhisar', 'Hüyük', 'Hadim', 'Taşkent', 'Yunak', 'Altınekin', 'Tuzlukçu', 'Güneysınır', 'Derbent', 'Emirgazi', 'Halkapınar', 'Ahırlı', 'Akören', 'Derebucak', 'Yalıhüyük'],
  'Kütahya': ['Merkez', 'Tavşanlı', 'Simav', 'Gediz', 'Emet', 'Altıntaş', 'Domaniç', 'Hisarcık', 'Aslanapa', 'Çavdarhisar', 'Dumlupınar', 'Pazarlar', 'Şaphane'],
  'Malatya': ['Battalgazi', 'Yeşilyurt', 'Doğanşehir', 'Akçadağ', 'Darende', 'Hekimhan', 'Arapgir', 'Yazıhan', 'Arguvan', 'Pütürge', 'Kuluncak', 'Kale', 'Doğanyol'],
  'Manisa': ['Yunusemre', 'Şehzadeler', 'Turgutlu', 'Akhisar', 'Salihli', 'Soma', 'Saruhanlı', 'Kırkağaç', 'Demirci', 'Gördes', 'Sarıgöl', 'Alaşehir', 'Kula', 'Selendi', 'Ahmetli', 'Gölmarmara', 'Köprübaşı'],
  'Mardin': ['Artuklu', 'Kızıltepe', 'Nusaybin', 'Midyat', 'Derik', 'Savur', 'Dargeçit', 'Mazıdağı', 'Ömerli', 'Yeşilli'],
  'Mersin': ['Yenişehir', 'Mezitli', 'Akdeniz', 'Toroslar', 'Tarsus', 'Erdemli', 'Silifke', 'Anamur', 'Mut', 'Gülnar', 'Aydıncık', 'Bozyazı', 'Çamlıyayla'],
  'Muğla': ['Menteşe', 'Bodrum', 'Fethiye', 'Marmaris', 'Milas', 'Dalaman', 'Datça', 'Ortaca', 'Köyceğiz', 'Yatağan', 'Ula', 'Kavaklıdere', 'Seydikemer'],
  'Muş': ['Merkez', 'Bulanık', 'Malazgirt', 'Varto', 'Hasköy', 'Korkut'],
  'Nevşehir': ['Merkez', 'Ürgüp', 'Avanos', 'Gülşehir', 'Kozaklı', 'Acıgöl', 'Derinkuyu', 'Hacıbektaş'],
  'Niğde': ['Merkez', 'Bor', 'Çamardı', 'Ulukışla', 'Altunhisar', 'Çiftlik'],
  'Ordu': ['Altınordu', 'Ünye', 'Fatsa', 'Perşembe', 'Kumru', 'Korgan', 'Mesudiye', 'Gölköy', 'Ulubey', 'Gülyalı', 'Kabadüz', 'Kabataş', 'Gürgentepe', 'Çamaş', 'Çatalpınar', 'Aybastı', 'Akkuş', 'İkizce', 'Çaybaşı'],
  'Osmaniye': ['Merkez', 'Kadirli', 'Düziçi', 'Bahçe', 'Hasanbeyli', 'Sumbas', 'Toprakkale'],
  'Rize': ['Merkez', 'Çamlıhemşin', 'Ardeşen', 'Pazar', 'Çayeli', 'Fındıklı', 'İkizdere', 'Derepazarı', 'Güneysu', 'Hemşin', 'İyidere', 'Kalkandere'],
  'Sakarya': ['Adapazarı', 'Serdivan', 'Erenler', 'Akyazı', 'Hendek', 'Sapanca', 'Geyve', 'Kaynarca', 'Karasu', 'Söğütlü', 'Taraklı', 'Pamukova', 'Ferizli', 'Karapürçek', 'Kocaali'],
  'Samsun': ['İlkadım', 'Atakum', 'Canik', 'Tekkeköy', 'Bafra', 'Çarşamba', 'Terme', 'Vezirköprü', 'Havza', 'Ladik', 'Kavak', 'Alaçam', 'Ayvacık', 'Asarcık', 'Salıpazarı', 'Yakakent', '19 Mayıs'],
  'Siirt': ['Merkez', 'Kurtalan', 'Baykan', 'Pervari', 'Eruh', 'Şirvan', 'Tillo'],
  'Sinop': ['Merkez', 'Boyabat', 'Gerze', 'Ayancık', 'Durağan', 'Türkeli', 'Dikmen', 'Erfelek', 'Saraydüzü'],
  'Sivas': ['Merkez', 'Şarkışla', 'Suşehri', 'Zara', 'Kangal', 'Gemerek', 'Divriği', 'Gürün', 'Hafik', 'Yıldızeli', 'İmranlı', 'Koyulhisar', 'Altınyayla', 'Akıncılar', 'Doğanşar', 'Gölova', 'Ulaş'],
  'Şanlıurfa': ['Eyyübiye', 'Haliliye', 'Karaköprü', 'Viranşehir', 'Siverek', 'Suruç', 'Akçakale', 'Birecik', 'Bozova', 'Ceylanpınar', 'Halfeti', 'Harran', 'Hilvan'],
  'Şırnak': ['Merkez', 'Cizre', 'Silopi', 'İdil', 'Uludere', 'Beytüşşebap', 'Güçlükonak'],
  'Tekirdağ': ['Süleymanpaşa', 'Çorlu', 'Çerkezköy', 'Ergene', 'Malkara', 'Muratlı', 'Hayrabolu', 'Şarköy', 'Saray', 'Marmaraereğlisi'],
  'Tokat': ['Merkez', 'Erbaa', 'Turhal', 'Niksar', 'Zile', 'Reşadiye', 'Almus', 'Artova', 'Pazar', 'Başçiftlik', 'Sulusaray', 'Yeşilyurt'],
  'Trabzon': ['Ortahisar', 'Akçaabat', 'Yomra', 'Araklı', 'Of', 'Sürmene', 'Vakfıkebir', 'Beşikdüzü', 'Çaykara', 'Maçka', 'Arsin', 'Tonya', 'Düzköy', 'Şalpazarı', 'Hayrat', 'Dernekpazarı', 'Köprübaşı', 'Çarşıbaşı'],
  'Tunceli': ['Merkez', 'Pertek', 'Hozat', 'Çemişgezek', 'Ovacık', 'Mazgirt', 'Pülümür', 'Nazımiye'],
  'Uşak': ['Merkez', 'Banaz', 'Eşme', 'Sivaslı', 'Karahallı', 'Ulubey'],
  'Van': ['İpekyolu', 'Tuşba', 'Edremit', 'Erciş', 'Çaldıran', 'Özalp', 'Başkale', 'Gürpınar', 'Muradiye', 'Gevaş', 'Bahçesaray', 'Saray', 'Çatak'],
  'Yalova': ['Merkez', 'Çınarcık', 'Altınova', 'Armutlu', 'Termal', 'Çiftlikköy'],
  'Yozgat': ['Merkez', 'Sorgun', 'Boğazlıyan', 'Akdağmadeni', 'Yerköy', 'Sarıkaya', 'Çekerek', 'Şefaatli', 'Aydıncık', 'Çandır', 'Çayıralan', 'Kadışehri', 'Saraykent', 'Yenifakılı'],
  'Zonguldak': ['Merkez', 'Ereğli', 'Çaycuma', 'Devrek', 'Alaplı', 'Gökçebey', 'Kilimli', 'Kozlu'],
};

// İl adlarını alfabetik sıralı olarak döndür
export const SORTED_CITIES = Object.keys(CITY_DISTRICTS).sort((a, b) =>
  a.localeCompare(b, 'tr')
);
